### ISSUE TITLE
Class Project

### ISSUE THREAD

**Issue by hollygene** [hollygene/Dosage_Compensation#1]
My plan for my class project is to create a pipeline for RNAseq data from aneuploid yeast. The dataset I am working with consists of paired-end RNAseq data from two different experiments: one mutation accumulation experiment with a highly homozygous, lab-strain ancestor, and another with a highly heterozygous, hybrid ancestor. Between these two experiments, I will be analyzing 43 aneuploid strains for 9 of the 16 chromosomes. Some of the lines overlap with each other as to what chromosome they are aneuploid for, and some have multiple aneuploidies. Further, some lines have one trisomy and one monosomy, or two trisomies. The number of trisomies greatly outnumbers the amount of monosomies.
I plan to use Tophat and Cufflinks to map reads, assemble the transcripts, and find differentially expressed genes. I plan to use Cuffdiff to find differentially expressed genes, and compare these results to those generated from edgeR. For each strain, I will compare the normalized gene expression value of each gene to that of the ancestor. I expect that aneuploid strains will have more differentially expressed genes on the aneuploid chromosome(s) than the euploid strains, and will potentially have trans-acting effects on other chromosomes. 
At the end of the project I plan to have results as to what genes in what genetic/ploidy backgrounds are differentially (or not!) expressed compared to the ancestral strains. Following this, I plan to screen for dosage compensation by eliminating the differentially expressed genes and solely looking at genes that do not have statistically significant differential gene expression compared to the ancestor. Once I find these genes, I will determine what chromosome they reside on, whether they are part of a "dosage-sensitive" suite of genes, and whether they contribute to the environmental stress response often produced by aneuploid yeast.

**Comment by cbergman** [comment]
- Sounds ambitious, but important for your thesis. I would start developing your pipeline with just one pair of samples from one strain, then scale up to include mutiple pairs of samples
- Can you transfer your data to sapleo/zcluster and post the location of the raw data on sapleo/zcluster
- Also, can you post information on the library prep and how the samples were run (multiplexing, number of Illumina runs)
- I would transfer data for all samples at once with rsync, but only start analysing one pair a the beginning
- After you transfer your data, I would run fastqc on the data as a preliminary check to see if you need to adaptor or paluity trim your data.
- Then, I would map the reads with BWA or Bowtie. You probably can get away with not using a splice aware mapper since yeast has so few introns. You might want to check a few yeast RNA-seq papers to see what they use.

**Comment by hollygene** [comment]
Location of my data on Sapelo:
**/lustre1/hcm14449/SC_RNAseq/RNA_seq/November_2017_Assembly/GC**
This directory is full of .fastq files from samples that were descended from the highly heterozygous ancestor (as well as the ancestor)
**/lustre1/hcm14449/SC_RNAseq/RNA_seq/November_2017_Assembly/MA_new**
This directory is full of .fastq files from samples that were descended from the highly homozygous ancestor. These samples and the GC samples were sequenced at the same time. 
**/lustre1/hcm14449/SC_RNAseq/RNA_seq/November_2017_Assembly/MA_old**
This directory is full of .fastq files from samples that were also descended from the highly homozygous ancestor, but the RNA was extracted and sequenced approximately one year before the others.

**Comment by hollygene** [comment]
Libraries for the GC and MA_new samples were prepped using the Illumina Stranded RNAseq kit.
They were then sequenced at the Georgia Genomics Facility on the Illumina NextSeq (75 Cycles) SE75 High Output flow cell. Samples were multiplexed, and split across two runs.

**Comment by hollygene** [comment]
Ran fastQC on GC lines only
Link to script used:
6e5727d821ab96d33a571c6bcad1c20f757ffa05 
Links to fastQC output files for Line 2:
https://github.com/hollygene/Dosage_Compensation/blob/master/Holly_2A_S1_R1_001_fastqc.html
https://github.com/hollygene/Dosage_Compensation/blob/master/Holly_2B_S7_R1_001_fastqc.html
https://github.com/hollygene/Dosage_Compensation/blob/master/Holly_2C_S4_R1_001_fastqc.html

Notes on how fastQC output looks:
Nothing super concerning with each replicate. There are no adapters to remove. However, there are Kmers and the per base sequence content is variable up until around base 10. The documentation says that this doesn't usually make much of a difference, but using Trimmomatic I'm pretty sure I can trim off the first 10 bases if I need to.

**Comment by hollygene** [comment]
Updates so far: 
Ran Trimgalore, Tophat, and Cufflinks on GC lines succesfully
Ran Trimgalore and Tophat on MA_old and MA_new lines successfully
Script in the queue now is trying to run Cuffquant on GC lines, and Cufflinks on MA_old and MA_new lines 

Also working on writing the introduction/methods for the class paper.

**Comment by cbergman** [comment]
- Sounds like you are making good progress
- Based on waht another student said it looks like GGF may do adapter/quality timming before giving data back to you, which may be why your fastQC reports look good. You might want to look into what GGF sent you initially to make sure about this.

**Comment by hollygene** [comment]
Thanks Casey! Sorry I haven't been to class, it's been easier for me to work with two monitors in lab. I'll look into GGF, thanks!
